#!/usr/bin/env bash
# ─────────────────────────────────────────────
#  Tor Control Center v2 — Setup
#  Ubuntu / Debian / Arch / Fedora
# ─────────────────────────────────────────────
set -euo pipefail

G='\033[0;32m'; Y='\033[1;33m'; R='\033[0;31m'; N='\033[0m'
ok()   { echo -e "${G}[✓]${N} $*"; }
warn() { echo -e "${Y}[!]${N} $*"; }
err()  { echo -e "${R}[✗]${N} $*"; exit 1; }

echo ""
echo "  🧅  Tor Control Center v2 — Setup"
echo "  ──────────────────────────────────"
echo ""

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ── package manager ───────────────────────────────────────────────────────────
if   command -v apt-get &>/dev/null; then PM="apt"
elif command -v pacman  &>/dev/null; then PM="pacman"
elif command -v dnf     &>/dev/null; then PM="dnf"
else warn "Unknown package manager — install deps manually."; PM="none"; fi

# ── system packages ───────────────────────────────────────────────────────────
ok "Installing system packages ($PM)…"
case $PM in
  apt)
    sudo apt-get update -qq
    sudo apt-get install -y tor python3-pip \
      python3-pyqt6 python3-requests >/dev/null 2>&1 || true
    ;;
  pacman)
    sudo pacman -Sy --noconfirm tor python-pyqt6 python-requests >/dev/null 2>&1 || true
    ;;
  dnf)
    sudo dnf install -y tor python3-PyQt6 python3-requests >/dev/null 2>&1 || true
    ;;
esac

# ── pip packages ──────────────────────────────────────────────────────────────
python3 -c "import PyQt6"   2>/dev/null || {
  warn "PyQt6 not found via system, trying pip…"
  pip3 install PyQt6 --break-system-packages -q
}
python3 -c "import requests" 2>/dev/null || {
  warn "requests not found, installing…"
  pip3 install requests --break-system-packages -q
}
python3 -c "import socks"   2>/dev/null || {
  ok "Installing PySocks (SOCKS5 support)…"
  pip3 install "requests[socks]" --break-system-packages -q
}
ok "Python dependencies ready"

# ── tor service ───────────────────────────────────────────────────────────────
# Do NOT enable autostart — user controls this manually via the app
ok "Tor installed (service left disabled — start via app)"

# ── sudoers ───────────────────────────────────────────────────────────────────
SUDOERS="/etc/sudoers.d/tor-control-center"
if [[ ! -f "$SUDOERS" ]]; then
  ok "Adding sudoers rule (passwordless tor + iptables)…"
  cat <<RULE | sudo tee "$SUDOERS" >/dev/null
# Tor Control Center — generated by setup_tor_tray.sh
$USER ALL=(ALL) NOPASSWD: \
  /usr/bin/systemctl start tor, \
  /usr/bin/systemctl stop tor, \
  /usr/bin/systemctl restart tor, \
  /sbin/iptables, \
  /usr/sbin/iptables, \
  /sbin/ip6tables, \
  /usr/sbin/ip6tables
RULE
  sudo chmod 440 "$SUDOERS"
else
  warn "Sudoers rule already exists — skipped"
fi

# ── install script ────────────────────────────────────────────────────────────
DEST="$HOME/.local/bin/tor_tray.py"
mkdir -p "$HOME/.local/bin"
cp "$SCRIPT_DIR/tor_tray.py" "$DEST"
chmod +x "$DEST"
ok "Script installed → $DEST"

# ── XDG autostart (KDE / GNOME) ───────────────────────────────────────────────
mkdir -p "$HOME/.config/autostart"
cat > "$HOME/.config/autostart/tor-control-center.desktop" <<DESK
[Desktop Entry]
Type=Application
Name=Tor Control Center
Comment=Tor monitor — starts minimized in tray, does not start Tor automatically
Exec=python3 $DEST
Icon=network-vpn
Categories=Network;Security;
Terminal=false
StartupNotify=false
X-GNOME-Autostart-enabled=true
DESK
ok "Autostart entry created (tray only, Tor stays off)"

# ── app launcher ──────────────────────────────────────────────────────────────
mkdir -p "$HOME/.local/share/applications"
cat > "$HOME/.local/share/applications/tor-control-center.desktop" <<DESK
[Desktop Entry]
Type=Application
Name=Tor Control Center
Comment=KDE/GNOME system tray for Tor monitoring and control
Exec=python3 $DEST
Icon=network-vpn
Categories=Network;Security;
Terminal=false
StartupNotify=false
DESK
ok "App launcher created"

# ── torrc hint ────────────────────────────────────────────────────────────────
TORRC="/etc/tor/torrc"
if [[ -f "$TORRC" ]] && ! grep -q "^ControlPort" "$TORRC"; then
  echo ""
  warn "Optional: enable Tor control port for 'New Identity':"
  echo "  sudo bash -c 'echo -e \"ControlPort 9051\nCookieAuthentication 0\" >> /etc/tor/torrc'"
  echo "  sudo systemctl restart tor"
fi

echo ""
echo "  ──────────────────────────────────────────────"
ok "Setup complete!"
echo ""
echo "  Start now:    python3 ~/.local/bin/tor_tray.py"
echo "  Auto-starts:  at login (tray only, Tor off)"
echo "  ──────────────────────────────────────────────"
echo ""
